version: "3.4"

services:
  quiz:
    image: quiz
    build: ./web/Dockerfile
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - ./Content:/data
    environment:
      ConnectionStrings__DatabaseURL: Host=db;Database=quiz;Username=quiz;Password=quiz123
  db:
    image: postgres:11.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: quiz
      POSTGRES_PASSWORD: quiz123
