name: Push-beta

on:
  push:
    branches:
      - beta
jobs:
  build:
    env:
      DOCKER_REPOSITORY: ghcr.io
      IMAGE: idp
    name: Build and push
    runs-on: ubuntu-latest
    # needs: [test]
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Login docker repository
        run: echo ${{ secrets.CR_PAT }} | docker login $DOCKER_REPOSITORY -u $GITHUB_ACTOR --password-stdin
      - uses: FranzDiebold/github-env-vars-action@v2
      # Build the Docker image
      - name: Build and Push
        run: |
          echo "build and push $DOCKER_REPOSITORY/$CI_REPOSITORY_OWNER/$IMAGE:beta"
          docker build -t $DOCKER_REPOSITORY/$CI_REPOSITORY_OWNER/$IMAGE:beta .
          docker push $DOCKER_REPOSITORY/$CI_REPOSITORY_OWNER/$IMAGE:beta
